.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PRLBACKUP" "1" "May 2012" "" "PRLBACKUP V1.3.0"
.
.SH "NAME"
\fBprlbackup\fR \- an awesome backup tool for Parallels Server Virtual Machines
.
.SH "SYNOPSIS"
\fBprlbackup\fR \fB\-h\fR|\fB\-\-help\fR
.
.br
\fBprlbackup\fR [\fIOPTIONS\fR\.\.\.] \fIvm_id|vm_name\fR\.\.\.
.
.br
\fBprlbackup\fR [\fIOPTIONS\fR\.\.\.] \fB\-a\fR|\fB\-\-all\fR
.
.br
\fBprlbackup\fR [\fIOPTIONS\fR\.\.\.] \fB\-a\fR|\fB\-\-all\fR \fB\-e\fR|\fB\-\-exclude\fR \fIvm_id|vm_name\fR\.\.\.
.
.SH "DESCRIPTION"
\fBprlbackup\fR simplifies the backup of one or multiple Virtual Machines (VM) running on Parallels Server by stoping them during backup and deleting old backups on demand\. A working installation of Parallels Server is required\.
.
.P
\fBprlbackup\fR was tested under Parallels Server for Mac 4\.0 (PSfM)\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display a short help\.
.
.TP
\fB\-a\fR, \fB\-\-all\fR
Backup all virtual machines which are registered in Parallels Server\.
.
.TP
\fB\-e\fR, \fB\-\-exclude\fR
Backup all but the given virtual machines (only applicable in combination with option \fB\-\-all\fR!)\.
.
.TP
\fB\-f\fR, \fB\-\-full\fR
Create full backups (by default incremental backups are created)\. Note that the first backup for a VM is always a full backup despide of this option\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Display commands before executing them\.
.
.TP
\fB\-n\fR, \fB\-\-dry\-run\fR
Don\'t run commands with an impact on VMs (display them instead)\.
.
.TP
\fB\-k\fR \fInumber_of_full_backups\fR, \fB\-\-keep\-only\fR \fInumber_of_full_backups\fR
Delete the oldest full backup(s) until only \fInumber_of_full_backups\fR exist\. This cleanup action will be executed for each VM right after creating the corresponding backup but only if the backup was successfully created\. Incremental backups are automatically deleted by Parallels Server when their full backup is deleted\.
.
.SH "EXAMPLES"
Display short help:
.
.IP "" 4
.
.nf

$ prlbackup \-\-help
.
.fi
.
.IP "" 0
.
.P
Backup VMs by name:
.
.IP "" 4
.
.nf

$ prlbackup Alpha Bravo Charlie
.
.fi
.
.IP "" 0
.
.P
Backup a VM by id:
.
.IP "" 4
.
.nf

$ prlbackup "{97351580\-afd7\-4aff\-9960\-814196b28e37}"
.
.fi
.
.IP "" 0
.
.P
Create full backups of all VMs
.
.IP "" 4
.
.nf

$ prlbackup \-\-full \-\-all
.
.fi
.
.IP "" 0
.
.P
Backup all but not the given VMs:
.
.IP "" 4
.
.nf

$ prlbackup \-\-all \-\-exclude Delta Echo
.
.fi
.
.IP "" 0
.
.P
Show what commands (with VM impact) whould have been run when backing up all VMs:
.
.IP "" 4
.
.nf

$ prlbackup \-\-dry\-run \-\-all
.
.fi
.
.IP "" 0
.
.P
Create the weekly full backup for all VMs and delete backups older than four weeks:
.
.IP "" 4
.
.nf

$ prlbackup \-\-all \-\-keep\-only 5
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
prlctl(8)
.
.IP "\(bu" 4
prlbackup on Github \fIhttps://github\.com/bjoernalbers/prlbackup\fR
.
.IP "" 0
.
.SH "COPYRIGHT"
Copyright (c) 2012 Bjoern Albers (\fIbjoernalbers@googlemail\.com\fR)
.
.P
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.
.P
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\.
.
.P
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\.
